# fly.toml app configuration file generated for calculator-winter-forest-3560 on 2024-12-15T06:19:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'calculator-winter-forest-3560'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[[mounts]]
  source = 'data'
  destination = '/data'

